"""Request payloads (TypedDicts) and response models (dataclasses) for the Midwater API.

Response models keep the full decoded JSON in ``raw`` so fields added to the API later are
reachable before the SDK names them. Enum-like fields are typed as ``Literal`` for editors, but
values added to the API later are passed through unchanged, never rejected.

Top-level response models also carry ``request_id``, read from the ``Midwater-Request-Id``
response header. The server doesn't send that header yet (it's planned), so it is ``None`` for
now.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional, TypedDict

__all__ = [
    "Channel",
    "Speaker",
    "EndedBy",
    "ConversationStatus",
    "Outcome",
    "CheckResultValue",
    "DecidedBy",
    "HealthStatus",
    "Environment",
    "FeedbackValue",
    "Turn",
    "Event",
    "AgentRef",
    "GroupRef",
    "ConversationCreate",
    "FeedbackCreate",
    "ConversationAccepted",
    "ConversationAgent",
    "GroupSummary",
    "CheckResult",
    "Coverage",
    "Conversation",
    "Feedback",
    "HealthWindow",
    "AgentHealth",
    "GroupHealthAgent",
    "GroupHealth",
    "WebhookEvent",
]

Channel = Literal["voice", "chat"]
Speaker = Literal["agent", "user", "human_agent"]
EndedBy = Literal["agent", "caller", "user", "human_agent", "timeout", "system"]
ConversationStatus = Literal["queued", "evaluating", "done", "failed"]
# Planned renames (accept both until announced): escalated -> handed_to_person,
# not_real_inquiry -> not_customer_call, llm_judge -> second_review.
Outcome = Optional[
    Literal[
        "resolved",
        "unresolved",
        "escalated",
        "not_real_inquiry",
        "handed_to_person",
        "not_customer_call",
    ]
]
CheckResultValue = Literal["pass", "fail", "uncertain", "not_applicable", "met", "not_met"]
DecidedBy = Optional[Literal["rule", "model", "llm_judge", "second_review", "human"]]
HealthStatus = Literal["healthy", "watch", "at_risk", "not_enough_calls"]
Environment = Literal["test", "live"]
FeedbackValue = Literal["pass", "fail"]


# --------------------------------------------------------------------------- request payloads


class _TurnRequired(TypedDict):
    speaker: Speaker
    text: str


class Turn(_TurnRequired, total=False):
    """One transcript turn."""

    start_ms: int
    end_ms: int
    asr_confidence: float


class _EventRequired(TypedDict):
    type: str


class Event(_EventRequired, total=False):
    """Something the agent did: a tool call, a transfer, a handoff. The API keeps extra keys."""

    name: str
    status: str
    target: str
    at_ms: int


class AgentRef(TypedDict, total=False):
    """The AI agent that handled the conversation. Omit it to use the project's Default agent."""

    id: str
    name: str
    version: str


class _GroupRefRequired(TypedDict):
    id: str


class GroupRef(_GroupRefRequired, total=False):
    """Files the agent into this group the first time the agent is seen without one."""

    name: str


class _ConversationCreateRequired(TypedDict):
    external_id: str
    channel: Channel
    transcript: List[Turn]


class ConversationCreate(_ConversationCreateRequired, total=False):
    """Body of ``POST /v1/conversations``."""

    started_at: str
    ended_at: str
    ended_by: EndedBy
    agent: AgentRef
    group: GroupRef
    events: List[Event]
    metadata: Dict[str, Any]


class _FeedbackCreateRequired(TypedDict):
    check_key: str
    verdict: FeedbackValue


class FeedbackCreate(_FeedbackCreateRequired, total=False):
    """Body of ``POST /v1/conversations/{id}/feedback``."""

    note: str


# --------------------------------------------------------------------------- response models


def _opt_str(value: Any) -> Optional[str]:
    return None if value is None else str(value)


def _opt_float(value: Any) -> Optional[float]:
    return None if value is None else float(value)


def _opt_int(value: Any) -> Optional[int]:
    return None if value is None else int(value)


@dataclass
class ConversationAccepted:
    """Answer to ``conversations.create()``.

    ``duplicate`` is true when the ``external_id`` already existed (HTTP 200, nothing new was
    created). ``replayed`` is true when the answer is a replay of an earlier request with the
    same ``Idempotency-Key``. ``idempotency_key`` is the key that was sent (generated by the
    SDK when you didn't pass one).
    """

    id: str
    status: ConversationStatus
    duplicate: bool = False
    replayed: bool = False
    idempotency_key: Optional[str] = None
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)
    request_id: Optional[str] = field(default=None, compare=False)

    @classmethod
    def from_dict(
        cls,
        data: Mapping[str, Any],
        *,
        replayed: bool = False,
        idempotency_key: Optional[str] = None,
    ) -> ConversationAccepted:
        return cls(
            id=str(data["id"]),
            status=data["status"],
            duplicate=bool(data.get("duplicate", False)),
            replayed=replayed,
            idempotency_key=idempotency_key,
            raw=dict(data),
        )


@dataclass
class ConversationAgent:
    id: str
    name: str
    version: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ConversationAgent:
        return cls(
            id=str(data["id"]),
            name=str(data.get("name", "")),
            version=_opt_str(data.get("version")),
        )


@dataclass
class GroupSummary:
    id: str
    name: str

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> GroupSummary:
        return cls(id=str(data["id"]), name=str(data.get("name", "")))

    @classmethod
    def from_optional(cls, data: Any) -> Optional[GroupSummary]:
        return cls.from_dict(data) if isinstance(data, Mapping) else None


@dataclass
class CheckResult:
    """The result of one check on one conversation.

    ``verdict`` is the check's result: ``pass`` (no problem found), ``fail`` (Midwater found
    this problem), ``uncertain`` (a person should look), ``not_applicable``, or ``met`` /
    ``not_met`` for gating questions. ``decided_by`` says how it was reached: ``rule`` (from
    the events you sent), ``model`` (Midwater's model read the conversation), ``llm_judge``
    (a second review for unclear conversations; planned rename ``second_review``) or ``human``.
    """

    check_key: str
    check_version: int
    check_status: str
    verdict: CheckResultValue
    # Midwater's opaque scoring version, e.g. "2026-10-06.3"; None when nothing scored the result.
    scorer_version: Optional[str]
    check_name: Optional[str] = None
    score: Optional[float] = None
    choice: Optional[str] = None
    decided_by: DecidedBy = None
    reason: Optional[str] = None
    evidence_turns: List[Any] = field(default_factory=list)
    latency_ms: Optional[int] = None
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CheckResult:
        return cls(
            check_key=str(data["check_key"]),
            check_version=int(data.get("check_version", 0)),
            check_status=str(data.get("check_status", "")),
            verdict=data["verdict"],
            scorer_version=_opt_str(data.get("scorer_version")),
            check_name=_opt_str(data.get("check_name")),
            score=_opt_float(data.get("score")),
            choice=_opt_str(data.get("choice")),
            decided_by=data.get("decided_by"),
            reason=_opt_str(data.get("reason")),
            evidence_turns=list(data.get("evidence_turns") or []),
            latency_ms=_opt_int(data.get("latency_ms")),
            raw=dict(data),
        )


@dataclass
class Coverage:
    """How much of the transcript Midwater read.

    A very long call can be read in part: one stretch from the middle is skipped and the opening
    and ending are kept, so checks answered from it may be incomplete. ``complete`` is ``True``
    when every turn was read. ``skipped_from`` / ``skipped_to`` are milliseconds from the start of
    the call (``None`` when complete, or when the turns have no times).
    """

    complete: bool
    skipped_turns: int = 0
    skipped_from: Optional[int] = None
    skipped_to: Optional[int] = None

    @classmethod
    def from_optional(cls, data: Optional[Mapping[str, Any]]) -> Optional[Coverage]:
        if not data:
            return None
        return cls(
            complete=bool(data.get("complete", True)),
            skipped_turns=int(data.get("skipped_turns") or 0),
            skipped_from=_opt_int(data.get("skipped_from")),
            skipped_to=_opt_int(data.get("skipped_to")),
        )


@dataclass
class Conversation:
    """A conversation, its scoring ``status``, its ``outcome`` and every check result.

    ``results`` fills in once ``status`` is ``done``.
    """

    id: str
    external_id: str
    channel: Channel
    status: ConversationStatus
    outcome: Outcome
    dashboard_url: str
    agent: ConversationAgent
    group: Optional[GroupSummary]
    transcript: List[Turn]
    events: List[Event]
    metadata: Dict[str, Any]
    results: List[CheckResult]
    started_at: Optional[str] = None
    ended_at: Optional[str] = None
    ended_by: Optional[str] = None
    # How much of the transcript was read (API 1.1.0). None from a server that doesn't send it.
    coverage: Optional[Coverage] = None
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)
    request_id: Optional[str] = field(default=None, compare=False)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Conversation:
        return cls(
            id=str(data["id"]),
            external_id=str(data.get("external_id", "")),
            channel=data.get("channel", "voice"),
            status=data["status"],
            outcome=data.get("outcome"),
            dashboard_url=str(data.get("dashboard_url", "")),
            agent=ConversationAgent.from_dict(data.get("agent") or {"id": ""}),
            group=GroupSummary.from_optional(data.get("group")),
            transcript=list(data.get("transcript") or []),
            events=list(data.get("events") or []),
            metadata=dict(data.get("metadata") or {}),
            results=[CheckResult.from_dict(r) for r in data.get("results") or []],
            started_at=_opt_str(data.get("started_at")),
            ended_at=_opt_str(data.get("ended_at")),
            ended_by=_opt_str(data.get("ended_by")),
            coverage=Coverage.from_optional(data.get("coverage")),
            raw=dict(data),
        )


@dataclass
class Feedback:
    """A stored label from ``conversations.feedback()``. ``source`` is always ``api``."""

    id: str
    check_key: str
    verdict: FeedbackValue
    source: str
    # True when the answer is a replay of an earlier request with the same Idempotency-Key.
    replayed: bool = False
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)
    request_id: Optional[str] = field(default=None, compare=False)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any], *, replayed: bool = False) -> Feedback:
        return cls(
            id=str(data["id"]),
            check_key=str(data["check_key"]),
            verdict=data["verdict"],
            source=str(data.get("source", "")),
            replayed=replayed,
            raw=dict(data),
        )


@dataclass
class HealthWindow:
    """Health totals over a 7- or 30-day window."""

    conversations: int
    with_outcome: int
    resolution_rate: Optional[float]
    handed_to_person_rate: Optional[float]
    requests_for_person_not_honored: int
    avg_frustration: Optional[float]
    compliance_failures: int
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> HealthWindow:
        return cls(
            conversations=int(data.get("conversations", 0)),
            with_outcome=int(data.get("with_outcome", 0)),
            resolution_rate=_opt_float(data.get("resolution_rate")),
            handed_to_person_rate=_opt_float(data.get("handed_to_person_rate")),
            requests_for_person_not_honored=int(data.get("requests_for_person_not_honored", 0)),
            avg_frustration=_opt_float(data.get("avg_frustration")),
            compliance_failures=int(data.get("compliance_failures", 0)),
            raw=dict(data),
        )


@dataclass
class AgentHealth:
    """An agent's health in the API key's environment."""

    agent_id: str
    name: str
    environment: Environment
    health_status: HealthStatus
    reason: str
    group: Optional[GroupSummary]
    last_7_days: HealthWindow
    last_30_days: HealthWindow
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)
    request_id: Optional[str] = field(default=None, compare=False)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> AgentHealth:
        return cls(
            agent_id=str(data["agent_id"]),
            name=str(data.get("name", "")),
            environment=data["environment"],
            health_status=data["health_status"],
            reason=str(data.get("reason", "")),
            group=GroupSummary.from_optional(data.get("group")),
            last_7_days=HealthWindow.from_dict(data.get("last_7_days") or {}),
            last_30_days=HealthWindow.from_dict(data.get("last_30_days") or {}),
            raw=dict(data),
        )


@dataclass
class GroupHealthAgent:
    id: str
    name: str
    health_status: HealthStatus

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> GroupHealthAgent:
        return cls(
            id=str(data["id"]),
            name=str(data.get("name", "")),
            health_status=data["health_status"],
        )


@dataclass
class GroupHealth:
    """A group's health: the worst status among its active agents, and totals across them."""

    group_id: str
    name: str
    environment: Environment
    health_status: HealthStatus
    reason: str
    agents: List[GroupHealthAgent]
    last_7_days: HealthWindow
    last_30_days: HealthWindow
    raw: Dict[str, Any] = field(default_factory=dict, repr=False, compare=False)
    request_id: Optional[str] = field(default=None, compare=False)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> GroupHealth:
        return cls(
            group_id=str(data["group_id"]),
            name=str(data.get("name", "")),
            environment=data["environment"],
            health_status=data["health_status"],
            reason=str(data.get("reason", "")),
            agents=[GroupHealthAgent.from_dict(a) for a in data.get("agents") or []],
            last_7_days=HealthWindow.from_dict(data.get("last_7_days") or {}),
            last_30_days=HealthWindow.from_dict(data.get("last_30_days") or {}),
            raw=dict(data),
        )


# --------------------------------------------------------------------------- webhooks


class WebhookEvent(TypedDict):
    """A verified webhook delivery, as returned by ``midwater.webhooks.verify()``.

    ``type`` is one of ``conversation.evaluated``, ``check.failed``, ``check.failed.digest``,
    ``agent.health_changed``, ``group.health_changed`` or ``test``; ``data`` depends on it
    (see the OpenAPI document in this repository). ``conversation.evaluated`` data carries
    ``coverage`` (see :class:`Coverage`) as a plain dict.
    """

    id: str
    type: str
    environment: Environment
    created_at: str
    data: Dict[str, Any]
